### PR TITLE
Added my solution to problem 15

### PR DESCRIPTION
**Pull request by osama-swe**

### CODE REVIEW

**Comment by aboelsooud** [comment]
Add some comments explaining your code please @osama-swe

**Comment by osama-swe** [comment]
I find that it is self explanatory. Isn't it?

**Comment by 7oSkaaa** [comment]
Not all people think like you. @osama-swe

**Comment by osama-swe** [comment]
done y4bab @aboelsooud @7oSkaaa 
34an 5aterko bas ;)

**Pull request merged**
